// Dummy data for the restaurant management system

export const menuItems = [
  {
    id: 1,
    name: "Margherita Pizza",
    category: "Pizza",
    price: 12.99,
    stock: 25,
    description: "Fresh tomatoes, mozzarella, basil",
    image: "/margherita-pizza.png",
  },
  {
    id: 2,
    name: "Caesar Salad",
    category: "Salads",
    price: 8.99,
    stock: 15,
    description: "Romaine lettuce, parmesan, croutons",
    image: "/caesar-salad.png",
  },
  {
    id: 3,
    name: "Grilled Salmon",
    category: "Main Course",
    price: 18.99,
    stock: 8,
    description: "Atlantic salmon with herbs",
    image: "/grilled-salmon-plate.png",
  },
  {
    id: 4,
    name: "Chocolate Cake",
    category: "Desserts",
    price: 6.99,
    stock: 12,
    description: "Rich chocolate layer cake",
    image: "/decadent-chocolate-cake.png",
  },
]

export const customers = [
  {
    id: 1,
    name: "Alice Johnson",
    phone: "+1 (555) 123-4567",
    email: "alice@example.com",
    address: "123 Main St, City, State 12345",
    billNo: "BILL-001",
    totalOrders: 15,
    lastOrder: "2024-01-15",
  },
  {
    id: 2,
    name: "Bob Smith",
    phone: "+1 (555) 987-6543",
    email: "bob@example.com",
    address: "456 Oak Ave, City, State 12345",
    billNo: "BILL-002",
    totalOrders: 8,
    lastOrder: "2024-01-14",
  },
  {
    id: 3,
    name: "Carol Davis",
    phone: "+1 (555) 456-7890",
    email: "carol@example.com",
    address: "789 Pine Rd, City, State 12345",
    billNo: "BILL-003",
    totalOrders: 22,
    lastOrder: "2024-01-16",
  },
]

export const orders = [
  {
    id: 1,
    orderNo: "ORD-001",
    customer: "Alice Johnson",
    items: ["Margherita Pizza", "Caesar Salad"],
    total: 21.98,
    status: "completed",
    date: "2024-01-15",
    time: "12:30 PM",
  },
  {
    id: 2,
    orderNo: "ORD-002",
    customer: "Bob Smith",
    items: ["Grilled Salmon", "Chocolate Cake"],
    total: 25.98,
    status: "preparing",
    date: "2024-01-16",
    time: "1:15 PM",
  },
  {
    id: 3,
    orderNo: "ORD-003",
    customer: "Carol Davis",
    items: ["Margherita Pizza", "Chocolate Cake"],
    total: 19.98,
    status: "pending",
    date: "2024-01-16",
    time: "2:00 PM",
  },
]

export const inventoryItems = [
  {
    id: 1,
    name: "Tomatoes",
    category: "Vegetables",
    currentStock: 50,
    minStock: 20,
    unit: "kg",
    supplier: "Fresh Farms Co.",
    lastRestocked: "2024-01-10",
  },
  {
    id: 2,
    name: "Mozzarella Cheese",
    category: "Dairy",
    currentStock: 15,
    minStock: 10,
    unit: "kg",
    supplier: "Dairy Best Ltd.",
    lastRestocked: "2024-01-12",
  },
  {
    id: 3,
    name: "Salmon Fillets",
    category: "Seafood",
    currentStock: 8,
    minStock: 15,
    unit: "pieces",
    supplier: "Ocean Fresh",
    lastRestocked: "2024-01-14",
  },
  {
    id: 4,
    name: "Flour",
    category: "Baking",
    currentStock: 25,
    minStock: 30,
    unit: "kg",
    supplier: "Mill & Co.",
    lastRestocked: "2024-01-08",
  },
]

export const dashboardStats = {
  totalSales: 15420.5,
  totalCustomers: 342,
  pendingOrders: 8,
  lowStockItems: 3,
  todayOrders: 24,
  monthlyRevenue: 45230.75,
  topSellingItem: "Margherita Pizza",
  averageOrderValue: 18.5,
}
